/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.*;
import Controller.*;

import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author andres.rubiano
 */
public class frmBusiness extends javax.swing.JFrame {
    ctlBusiness ctlEmpresa;
    LinkedList<clsCities> listaCiudades = new LinkedList<>();

    /**
     * Creates new form Business
     */
    public frmBusiness() {
        initComponents();
        this.ctlEmpresa = new ctlBusiness();
        this.listaCiudades = ctlEmpresa.ListCities();
        this.LlenarCombobox();
        this.llamarCamposEmpresa(1);        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNit = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        txtRazonSocial = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        btnBusinessAceptar = new javax.swing.JButton();
        btnBusinessCancelar = new javax.swing.JButton();
        cbxCiudad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracionde Compañia");

        lblNit.setText("Nit");

        lblRazonSocial.setText("Razon Social");

        lblDireccion.setText("Dirección");

        lblCiudad.setText("Ciudad");

        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });

        jLabel5.setText("Informacion Compañia");

        btnBusinessAceptar.setText("Aceptar");
        btnBusinessAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusinessAceptarActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(btnBusinessAceptar);

        btnBusinessCancelar.setText("Cancelar");
        btnBusinessCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusinessCancelarActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(btnBusinessCancelar);

        cbxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNit)
                            .addComponent(lblCiudad)
                            .addComponent(lblRazonSocial)
                            .addComponent(lblDireccion))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(txtNit, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(cbxCiudad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNit)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LlenarCombobox(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsCities ciudad : listaCiudades){
            String data = ciudad.getNameCity();
            modelo.addElement(data);
            index++;
        }
        cbxCiudad.setModel(modelo);
        
    }
    
    
    private boolean llamarCamposEmpresa(int codigo){

        clsBusiness empresa = (clsBusiness) ctlEmpresa.searchEmpresa(codigo);
        
        if (empresa == null){
            JOptionPane.showMessageDialog(this, "Base de datos vacia, por favor diligencie la empresa", "Ingresar Informacion Empresa", 2);
            return true;
        }else{

            txtNit.setText(empresa.getNit());
            txtRazonSocial.setText(empresa.getNameBusiness());
            txtDireccion.setText(empresa.getAddress());
            cbxCiudad.setSelectedItem(empresa.getCity());
            return false;
        }
    
    }
    
    

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void btnBusinessCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusinessCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnBusinessCancelarActionPerformed

    private void btnBusinessAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusinessAceptarActionPerformed

        if(txtNit.getText().equals("") || txtDireccion.getText().equals("")){
            try {
                String nit = txtNit.getText();
                String razonSocial = txtRazonSocial.getText();
                String direccion = txtDireccion.getText();
                String ciudad = cbxCiudad.getSelectedItem().toString();
                
                if (nit.equals("") || (razonSocial.equals("")) || (direccion.equals("")) || (ciudad.equals(""))){
                    JOptionPane.showMessageDialog(this, "Por favor diligencie todos los campos del formulario", "Informacion Incompleta", 1);
                }else{
                    clsBusiness Empresa = new clsBusiness(0, nit, razonSocial, direccion, ciudad);
                    ctlEmpresa.createEmpresa(Empresa);
                    JOptionPane.showMessageDialog(this, "Informacion registrada correctamente", "Registro Existoso", 1);
                }
            }catch(Exception error){
                JOptionPane.showMessageDialog(this, "Por favor agrege un Año Correcto", "Erro Año Mascota", 1);
            }

        }else{
            try {
                clsBusiness empresa = null;
                String nit = txtNit.getText();
                String razonSocial = txtRazonSocial.getText();
                String direccion = txtDireccion.getText();
                String ciudad = cbxCiudad.getSelectedItem().toString();
                
                    clsBusiness actualizarEmpresa = new clsBusiness(1, nit, razonSocial, direccion, ciudad);
                    ctlEmpresa.updateEmpresa(actualizarEmpresa);
                    JOptionPane.showMessageDialog(this, "Informacion registrada correctamente", "Registro Existoso", 1);
                
            }catch(Exception error){
                JOptionPane.showMessageDialog(this, "Por favor agrege un Año Correcto", "Erro Año Mascota", 1);
            }
        }
        
        
        
    }//GEN-LAST:event_btnBusinessAceptarActionPerformed

    private void cbxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCiudadActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_cbxCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBusiness.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBusiness().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusinessAceptar;
    private javax.swing.JButton btnBusinessCancelar;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
