/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Class.*;
import Controller.*;

/**
 *
 * @author andres.rubiano
 */
public class frmCities extends javax.swing.JFrame {

    ctlCities ctlCiudades;
    ctlDepartament ctlDepartamentos;
    LinkedList<clsDepartament> listaDepartamentos = new LinkedList<>();
    LinkedList<clsCities> listaCiudades = new LinkedList<>();
    DefaultTableModel modelTablaCiudades = new DefaultTableModel();

    /**
     * Creates new form frmCities
     */
    public frmCities() {
        initComponents();
        this.ctlCiudades = new ctlCities();
        this.ctlDepartamentos = new ctlDepartament();
        this.listaDepartamentos = ctlDepartamentos.ListDepartament();
        this.listaCiudades = ctlCiudades.ListCiudades();
        txtidCiudad.setVisible(false);
        this.LlenarCombobox();
        this.setEncabezado();
        this.setFilasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSplitPane4 = new javax.swing.JSplitPane();
        btnBusinessAceptar3 = new javax.swing.JButton();
        btnBusinessCancelar1 = new javax.swing.JButton();
        lblNit1 = new javax.swing.JLabel();
        lblRazonSocial1 = new javax.swing.JLabel();
        lblDireccion1 = new javax.swing.JLabel();
        txtRazonSocial1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        txtNit1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        FormListCiudades = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCiudades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtidCiudad = new javax.swing.JTextField();
        txtCodigoDaneMunicipio = new javax.swing.JTextField();
        txtNombreCiudad = new javax.swing.JTextField();
        lblCodigoDane = new javax.swing.JLabel();
        lblNombreCiudad = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        btnGuardarCiudad = new javax.swing.JButton();
        btnEliminarCiudad = new javax.swing.JButton();
        btnBuscarCiudad = new javax.swing.JButton();
        cbxDepartamento = new javax.swing.JComboBox<>();
        btnEditarCiudad = new javax.swing.JButton();

        jLabel6.setText("Informacion Ciudades");

        btnBusinessAceptar3.setText("Aceptar");
        jSplitPane4.setLeftComponent(btnBusinessAceptar3);

        btnBusinessCancelar1.setText("Cancelar");
        jSplitPane4.setRightComponent(btnBusinessCancelar1);

        lblNit1.setText("Codigo Dane");

        lblRazonSocial1.setText("Nombre Ciudad");

        lblDireccion1.setText("Departamento");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de Ciudades");

        FormListCiudades.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCiudades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblCiudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblCiudades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        FormListCiudades.addTab("Listado Ciudades", jPanel1);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Modulo Ciudades");

        txtidCiudad.setEditable(false);

        lblCodigoDane.setText("Codigo Dane");

        lblNombreCiudad.setText("Nombre Ciudad");

        lblDepartamento.setText("Departamento");

        btnGuardarCiudad.setText("Crear");
        btnGuardarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCiudadActionPerformed(evt);
            }
        });

        btnEliminarCiudad.setText("Eliminar");
        btnEliminarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCiudadActionPerformed(evt);
            }
        });

        btnBuscarCiudad.setText("Buscar");
        btnBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCiudadActionPerformed(evt);
            }
        });

        btnEditarCiudad.setText("Editar");
        btnEditarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnGuardarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditarCiudad)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtidCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreCiudad)
                                    .addComponent(lblCodigoDane))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigoDaneMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(lblDepartamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNombreCiudad))
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FormListCiudades)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoDane)
                    .addComponent(txtCodigoDaneMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartamento)
                    .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCiudad)
                            .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(FormListCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarCiudad)
                            .addComponent(btnBuscarCiudad)
                            .addComponent(btnEditarCiudad)
                            .addComponent(btnGuardarCiudad))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtidCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoDaneMunicipio.setText("");
        txtNombreCiudad.setText("");
        cbxDepartamento.setSelectedIndex(0);
    }

    private void LlenarCombobox(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsDepartament listDto : listaDepartamentos){
            String data = listDto.getNameDepartament();
            modelo.addElement(data);
            index++;
        }
        this.cbxDepartamento.setModel(modelo);
        
    }
    
    private void setEncabezado(){
        String[] cabecera = {"Codigo Dane", "Nombre Ciudad", "Departamento"};
        modelTablaCiudades.setColumnIdentifiers(cabecera);
        tblCiudades.setModel(modelTablaCiudades);
    }
    
    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaCiudades.getColumnCount()];
        int index = 1;
        
        for(clsCities listCiudad : listaCiudades){

            data[0] = listCiudad.getCodDane();
            data[1] = listCiudad.getNameCity();
            data[2] = listCiudad.getDepartamento().getNameDepartament();
            index++;
            modelTablaCiudades.addRow(data);
        }
        tblCiudades.setModel(modelTablaCiudades);
    }

    private void btnGuardarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCiudadActionPerformed
        try {
            String codigoDane = txtCodigoDaneMunicipio.getText();
            String nombreCiudad = txtNombreCiudad.getText();
            int idDepartamento = cbxDepartamento.getSelectedIndex();

            if(codigoDane.equals("") || nombreCiudad.equals("") || idDepartamento == 0){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos Codigo Dane, Nombre Ciudad y Departamento", "Error Informacion Ciudad", 1);

            }else{
                clsCities ciudad = new clsCities(0, nombreCiudad, codigoDane, idDepartamento, null);
                ctlCiudades.createCiudad(ciudad);
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
            
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnGuardarCiudadActionPerformed

    private void btnEditarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCiudadActionPerformed
        
        String codigoDane = txtCodigoDaneMunicipio.getText();
        String nombreCiudad = txtNombreCiudad.getText();
        int idDepartamento = cbxDepartamento.getSelectedIndex();
        try {
            
            int idCiudad = Integer.parseInt(txtidCiudad.getText());
            
            clsCities ciudades = new clsCities(idCiudad, nombreCiudad, codigoDane, idDepartamento, null);
            boolean respuesta = ctlCiudades.updateCiudad(ciudades);

            if(respuesta){
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarCiudadActionPerformed

    private void btnBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCiudadActionPerformed
        try {
            String codigoDane = txtCodigoDaneMunicipio.getText();
            clsCities ciudades = (clsCities) ctlCiudades.searchCiudad(codigoDane);

            if(ciudades == null){
                JOptionPane.showMessageDialog(this, "Codigo de Ciudad no Encontrado");
            }else{
                txtidCiudad.setText(ciudades.getIdCity()+"");
                txtCodigoDaneMunicipio.setText(ciudades.getCodDane());
                txtNombreCiudad.setText(ciudades.getNameCity());
                cbxDepartamento.setSelectedIndex(ciudades.getIdDepartament());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Ciudad", 1);
        }
    }//GEN-LAST:event_btnBuscarCiudadActionPerformed

    private void btnEliminarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCiudadActionPerformed
        try {
            String codigoDane = txtCodigoDaneMunicipio.getText();
            boolean respuesta = ctlCiudades.deleteCiudad(codigoDane);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Ciudad no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Ciudad", 1);
        }
    }//GEN-LAST:event_btnEliminarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane FormListCiudades;
    private javax.swing.JButton btnBuscarCiudad;
    private javax.swing.JButton btnBusinessAceptar3;
    private javax.swing.JButton btnBusinessCancelar1;
    private javax.swing.JButton btnEditarCiudad;
    private javax.swing.JButton btnEliminarCiudad;
    private javax.swing.JButton btnGuardarCiudad;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JLabel lblCodigoDane;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblNit1;
    private javax.swing.JLabel lblNombreCiudad;
    private javax.swing.JLabel lblRazonSocial1;
    private javax.swing.JTable tblCiudades;
    private javax.swing.JTextField txtCodigoDaneMunicipio;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtNit1;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtRazonSocial1;
    private javax.swing.JTextField txtidCiudad;
    // End of variables declaration//GEN-END:variables
}
