/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Class.clsDepartament;
import Controller.ctlDepartament;

/**
 *
 * @author andres.rubiano
 */
public class frmDepartament extends javax.swing.JFrame {

    ctlDepartament ctlDepartamentos;
    LinkedList<clsDepartament> listaDepartamentos = new LinkedList<>();
    DefaultTableModel modelTablaDepartamento = new DefaultTableModel();

    /**
     * Creates new form frmDepartament
     */
    public frmDepartament() {
        initComponents();
        this.ctlDepartamentos = new ctlDepartament();
        this.listaDepartamentos = ctlDepartamentos.ListDepartament();
        this.setEncabezado();
        this.setFilasTabla();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListDepartamento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoDaneDepartamento = new javax.swing.JTextField();
        txtNombreDepartamento = new javax.swing.JTextField();
        lblCodigoDane = new javax.swing.JLabel();
        lblNombreDepartamento = new javax.swing.JLabel();
        brnCrearDepartamento = new javax.swing.JButton();
        btnEliminarDepartamento = new javax.swing.JButton();
        btnBuscarDepartamento = new javax.swing.JButton();
        brnEditarDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de Departamentos");

        tblListDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListDepartamento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Departamento", jPanel1);

        lblCodigoDane.setText("Codigo Dane");

        lblNombreDepartamento.setText("Nombre Departamento");

        brnCrearDepartamento.setText("Crear");
        brnCrearDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCrearDepartamentoActionPerformed(evt);
            }
        });

        btnEliminarDepartamento.setText("Eliminar");
        btnEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepartamentoActionPerformed(evt);
            }
        });

        btnBuscarDepartamento.setText("Buscar");
        btnBuscarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepartamentoActionPerformed(evt);
            }
        });

        brnEditarDepartamento.setText("Editar");
        brnEditarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnEditarDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoDane)
                            .addComponent(lblNombreDepartamento))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoDaneDepartamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(brnCrearDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(brnEditarDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarDepartamento)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoDane)
                    .addComponent(txtCodigoDaneDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDepartamento)
                    .addComponent(txtNombreDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnCrearDepartamento)
                    .addComponent(btnEliminarDepartamento)
                    .addComponent(brnEditarDepartamento)
                    .addComponent(btnBuscarDepartamento))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoDaneDepartamento.setText("");
        txtNombreDepartamento.setText("");
        
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo Dane", "Nombre Departamento"};
        modelTablaDepartamento.setColumnIdentifiers(cabecera);
        tblListDepartamento.setModel(modelTablaDepartamento);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaDepartamento.getColumnCount()];
        int index = 1;
        
        for(clsDepartament listDto : listaDepartamentos){

            data[0] = listDto.getCodDane();
            data[1] = listDto.getNameDepartament();
            index++;
            modelTablaDepartamento.addRow(data);
        }
        tblListDepartamento.setModel(modelTablaDepartamento);
    }

    private void brnCrearDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCrearDepartamentoActionPerformed
        try {
            String codigoDane = txtCodigoDaneDepartamento.getText();
            String nomDepart = txtNombreDepartamento.getText();

            if(codigoDane.equals("") || nomDepart.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos Codigo Dane, Nombre Ciudad y Departamento", "Error Informacion Departamento", 1);
            }else{
                clsDepartament departamento = new clsDepartament(nomDepart, codigoDane);
                ctlDepartamentos.createDepartament(departamento);
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_brnCrearDepartamentoActionPerformed

    private void btnBuscarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepartamentoActionPerformed
        try {
            
            String codigoDane = txtCodigoDaneDepartamento.getText();
            clsDepartament departamento = (clsDepartament) ctlDepartamentos.searchDepartament(codigoDane);

            if(departamento == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
                
            }else{
                txtCodigoDaneDepartamento.setText(departamento.getCodDane());
                txtNombreDepartamento.setText(departamento.getNameDepartament());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Ciudad", 1);
        }
    }//GEN-LAST:event_btnBuscarDepartamentoActionPerformed

    private void brnEditarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnEditarDepartamentoActionPerformed
        String codigoDane = txtCodigoDaneDepartamento.getText();
        String nomDepart = txtNombreDepartamento.getText();

        try {
            clsDepartament departamento = new clsDepartament(nomDepart, codigoDane);
            boolean respuesta = ctlDepartamentos.updateDepartament(departamento);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_brnEditarDepartamentoActionPerformed

    private void btnEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepartamentoActionPerformed
        try {
            String codigoDane = txtCodigoDaneDepartamento.getText();
            boolean respuesta = ctlDepartamentos.deleteDepartament(codigoDane);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Departamento", 1);
        }
    }//GEN-LAST:event_btnEliminarDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDepartament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDepartament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDepartament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDepartament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDepartament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCrearDepartamento;
    private javax.swing.JButton brnEditarDepartamento;
    private javax.swing.JButton btnBuscarDepartamento;
    private javax.swing.JButton btnEliminarDepartamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoDane;
    private javax.swing.JLabel lblNombreDepartamento;
    private javax.swing.JTable tblListDepartamento;
    private javax.swing.JTextField txtCodigoDaneDepartamento;
    private javax.swing.JTextField txtNombreDepartamento;
    // End of variables declaration//GEN-END:variables
}
