/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.*;
import Controller.*;
import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres.rubiano
 */
public class frmEmployed extends javax.swing.JFrame {
//Instanciar controladores que se necesitan en el formulario empleado
    ctlEmployed ctlempleado;
    ctlCities ctlCiudades;
    ctlDepartament ctlDepartamentos;
    ctlTypeDocument ctlTipoDocumento;
    ctlGender ctlgenero;
    ctlStatusMarital ctlEstadoCivil;
//Instanciar las lista para los combobox
    LinkedList<clsDepartament> listaDepartamentos = new LinkedList<>();
    LinkedList<clsCities> listaCiudades = new LinkedList<>();
    LinkedList<clsTypeDocument> listaTipoDocumento = new LinkedList<>();
    LinkedList<clsGender> listagenero = new LinkedList<>();
    LinkedList<clsMaritalStatus> listaEstadoCivil = new LinkedList<>();
    DefaultTableModel ModeltablaEmpleados = new DefaultTableModel();

    
    /**
     * Creates new form Employed
     */
    public frmEmployed() {
        initComponents();
        this.ctlempleado = new ctlEmployed();
        this.ctlCiudades = new ctlCities();
        this.ctlDepartamentos = new ctlDepartament();
        this.ctlTipoDocumento = new ctlTypeDocument();
        this.ctlEstadoCivil = new ctlStatusMarital();
        this.ctlgenero = new ctlGender();
        this.listaDepartamentos = ctlDepartamentos.ListDepartament();
        this.listaCiudades = ctlCiudades.ListCiudades();
        this.listaTipoDocumento = ctlTipoDocumento.ListTipoDocumentos();
        this.listagenero = ctlgenero.ListGenero();
        this.listaEstadoCivil = ctlEstadoCivil.ListEstadoCivil();
        this.LlenarComboboxDepartamento();
        this.LlenarComboboxMunicipio();
        this.LlenarComboboxEstadoCivil();
        this.LlenarComboboxGenero();
        this.LlenarComboboxTipoDocumento();
        this.txtidEmpleado.setVisible(false);
        this.LlenarTablaEmpleados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblTipoDocumento = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        lblNumeroDocumento = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox<>();
        lblPrimerNombre = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        lblSegundoNombre = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        lblPrimerApellido = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        lblSegundoApellido = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        cbxGenero = new javax.swing.JComboBox<>();
        lblEstadoCivil = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        txtidEmpleado = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblBarrio = new javax.swing.JLabel();
        txtBarrio = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        cbxCiudad = new javax.swing.JComboBox<>();
        lblDepartamento = new javax.swing.JLabel();
        cbxDepartamento = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblTelefonoFijo = new javax.swing.JLabel();
        txtTelefonoFijo = new javax.swing.JTextField();
        lblTelefonoMovil = new javax.swing.JLabel();
        txtTelefonoMovil = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnCrearEmpleado = new javax.swing.JButton();
        btnEditarEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusable(false);

        lblTipoDocumento.setText("Tipo Documento");

        lblNumeroDocumento.setText("Numero Documento");

        lblPrimerNombre.setText("Primer Nombre");

        lblSegundoNombre.setText("Segundo Nombre");

        lblPrimerApellido.setText("Primer Apellido");

        lblSegundoApellido.setText("Segundo Apellido");

        lblFechaNacimiento.setText("Fecha de Nacimiento");

        lblGenero.setText("Genero");

        lblEstadoCivil.setText("Estado Civil");

        txtidEmpleado.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoDocumento)
                                    .addComponent(lblPrimerNombre)
                                    .addComponent(lblPrimerApellido))
                                .addGap(35, 35, 35))
                            .addComponent(lblEstadoCivil)
                            .addComponent(lblFechaNacimiento))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrimerNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, 0, 123, Short.MAX_VALUE)
                            .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrimerApellido))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSegundoNombre)
                                    .addComponent(lblSegundoApellido)
                                    .addComponent(lblGenero))
                                .addGap(16, 16, 16))
                            .addComponent(lblNumeroDocumento))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSegundoApellido)
                            .addComponent(txtSegundoNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 563, Short.MAX_VALUE)
                        .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumento)
                    .addComponent(lblNumeroDocumento)
                    .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundoNombre)
                    .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrimerNombre))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimerApellido)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSegundoApellido)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimiento)
                    .addComponent(lblGenero)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(txtidEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Empleado", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDireccion.setText("Direccion");

        lblBarrio.setText("Barrio");

        lblCiudad.setText("Ciudad");

        lblDepartamento.setText("Departamento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDepartamento)
                        .addGap(26, 26, 26)
                        .addComponent(cbxDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDireccion)
                            .addComponent(lblBarrio)
                            .addComponent(lblCiudad, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBarrio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBarrio)
                    .addComponent(txtBarrio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cbxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCiudad)
                    .addComponent(cbxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Direccion", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTelefonoFijo.setText("Telefono Fijo");

        lblTelefonoMovil.setText("Telefono Movil");

        lblCorreo.setText("Correo Electronico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoFijo)
                    .addComponent(lblCorreo)
                    .addComponent(lblTelefonoMovil))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoFijo)
                    .addComponent(txtTelefonoMovil)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoFijo)
                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoMovil)
                    .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Contacto", jPanel3);

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listado Empleados", jPanel4);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Hoja de Vida Empleado");

        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search-Male-User.png"))); // NOI18N
        btnBuscarEmpleado.setBorder(null);
        btnBuscarEmpleado.setBorderPainted(false);
        btnBuscarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEmpleado.setMaximumSize(new java.awt.Dimension(38, 38));
        btnBuscarEmpleado.setMinimumSize(new java.awt.Dimension(38, 38));
        btnBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEmpleadoActionPerformed(evt);
            }
        });

        btnCrearEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add-Male-User.png"))); // NOI18N
        btnCrearEmpleado.setBorder(null);
        btnCrearEmpleado.setBorderPainted(false);
        btnCrearEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEmpleadoActionPerformed(evt);
            }
        });

        btnEditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit-Male-User.png"))); // NOI18N
        btnEditarEmpleado.setBorder(null);
        btnEditarEmpleado.setBorderPainted(false);
        btnEditarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpleadoActionPerformed(evt);
            }
        });

        btnEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Remove-Male-User.png"))); // NOI18N
        btnEliminarEmpleado.setBorder(null);
        btnEliminarEmpleado.setBorderPainted(false);
        btnEliminarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarEmpleado.setMaximumSize(new java.awt.Dimension(34, 34));
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEditarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCrearEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LlenarComboboxDepartamento(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsDepartament listDto : listaDepartamentos){
                String data = listDto.getNameDepartament();
                modelo.addElement(data);
            index++;
        }
        this.cbxDepartamento.setModel(modelo);
    }

    private void LlenarTablaEmpleados(){
        LinkedList<clsEmployed> listaEmpleados = ctlempleado.ListEmpleado();
        String [] encabezadoTabla = {"Tipo Documento","Nombres Apellidos","Cumpleaños","Direccion","Barrio","Tel Fijo","Celular","Correo","tipo Documento",
        "Empresa","EstadoCivil","Genero","Cuidad","Departamento"};
        ModeltablaEmpleados.setColumnIdentifiers(encabezadoTabla);
        tblEmpleados.setModel(ModeltablaEmpleados);

        Object[] data = new Object[ModeltablaEmpleados.getColumnCount()];
        int index = 0;

        for(clsEmployed list : listaEmpleados){
            data[0] = list.getIdentityNumber();
            data[1] = list.getFirtsName() + " " +list.getSecondName() + " " + list.getFirtsLastname() + " " + list.getSecondLastname();
            data[2] = list.getBirthDate();
            data[3] = list.getAddress();
            data[4] = list.getNeighborhood();
            data[5] = list.getPhone();
            data[6] = list.getCellphone();
            data[7] = list.getEmail();
            data[8] = list.getIdIdentityType();
            data[9] = list.getIdBusiness();
            data[10] = list.getIdMaritalStatus();
            data[11] = list.getIdGender();
            data[12] = list.getIdCity();
            data[13] = list.getDepartamento().getNameDepartament();
            index++;
            ModeltablaEmpleados.addRow(data);
        }
        tblEmpleados.setModel(ModeltablaEmpleados);       
    }
    
    private void LlenarComboboxMunicipio(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsCities listaCiudades : listaCiudades){
                String data = listaCiudades.getNameCity();
                modelo.addElement(data);    
                index++;
        } 
        this.cbxCiudad.setModel(modelo);       
    }
    private void LlenarComboboxGenero(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsGender listGenero : listagenero){
                String data = listGenero.getNameGender();
                modelo.addElement(data);
            index++;
        }
        this.cbxGenero.setModel(modelo);
    }
    private void LlenarComboboxTipoDocumento(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsTypeDocument listaTDocumento : listaTipoDocumento){
                String data = listaTDocumento.getNameDocument();
                modelo.addElement(data);
            index++;
        }
        this.cbxTipoDocumento.setModel(modelo); 
    }
    private void LlenarComboboxEstadoCivil(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsMaritalStatus listaEstadoCivil : listaEstadoCivil){
                String data = listaEstadoCivil.getNameStatus();
                modelo.addElement(data);
            index++;
        }
        this.cbxEstadoCivil.setModel(modelo);;
    }

    private void limpiarCampos(){
        txtidEmpleado.setText("");
        txtBarrio.setText("");
        txtBuscar.setText("");
        txtDireccion.setText("");
        txtEmail.setText("");
        txtNumeroDocumento.setText("");
        txtPrimerApellido.setText("");
        txtPrimerNombre.setText("");
        txtSegundoApellido.setText("");
        txtSegundoNombre.setText("");
        txtTelefonoFijo.setText("");
        txtTelefonoMovil.setText("");
        cbxCiudad.setSelectedIndex(0);
        cbxDepartamento.setSelectedIndex(0);
        cbxEstadoCivil.setSelectedIndex(0);
        txtFechaNacimiento.setText("");
        cbxGenero.setSelectedIndex(0);
        cbxTipoDocumento.setSelectedIndex(0);
        
    }

    private void btnCrearEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEmpleadoActionPerformed
        try {
            String numeroDoc = txtNumeroDocumento.getText();
            String primerNom = txtPrimerNombre.getText();
            String segundNom = txtSegundoNombre.getText();
            String primerApell = txtPrimerApellido.getText();
            String segundoApell = txtSegundoApellido.getText();
            String fechaNacimiento = txtFechaNacimiento.getText();
            String direccion = txtDireccion.getText();
            String barrio = txtBarrio.getText();
            String telFijo = txtTelefonoFijo.getText();
            String celular = txtTelefonoMovil.getText();
            String correo = txtEmail.getText();
            int idTipoDocumento = cbxTipoDocumento.getSelectedIndex();
            int idEmpresa = 1;
            int idEstadoCivil = cbxEstadoCivil.getSelectedIndex();
            int idGenero = cbxGenero.getSelectedIndex();
            int idCiudad = cbxCiudad.getSelectedIndex();
            int idDepartamento = cbxDepartamento.getSelectedIndex();


            if(numeroDoc.equals("") || primerNom.equals("") || primerApell.equals("") || direccion.equals("") || correo.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos de Empleado", "Error Informacion Empleado", 1);

            }else{
                clsEmployed empleado = new clsEmployed(0, numeroDoc, primerNom, segundNom, primerApell, segundoApell, fechaNacimiento, direccion, barrio, telFijo, celular, correo, idTipoDocumento, idEmpresa, idEstadoCivil, idGenero, idCiudad, idDepartamento, null);
                ctlempleado.createEmpleado(empleado);
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
            
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnCrearEmpleadoActionPerformed

    private void btnBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoActionPerformed
        try {
            
            String numeroDoc = txtBuscar.getText();
            clsEmployed empleado = (clsEmployed) ctlempleado.searchEmpleado(numeroDoc);

            if(empleado == null){
                
                JOptionPane.showMessageDialog(this, "Numero documento Empleado no Encontrado");
                
            }else{
                txtidEmpleado.setText(empleado.getIdEmployed()+"");
                txtNumeroDocumento.setText(empleado.getIdentityNumber());
                txtPrimerNombre.setText(empleado.getFirtsName());
                txtSegundoNombre.setText(empleado.getSecondName());
                txtPrimerApellido.setText(empleado.getFirtsLastname());
                txtSegundoApellido.setText(empleado.getSecondLastname());
                txtFechaNacimiento.setText(empleado.getBirthDate());
                txtDireccion.setText(empleado.getAddress());
                txtBarrio.setText(empleado.getNeighborhood());
                txtTelefonoFijo.setText(empleado.getPhone());
                txtTelefonoMovil.setText(empleado.getCellphone());
                txtEmail.setText(empleado.getEmail());
                cbxCiudad.setSelectedIndex(empleado.getIdCity());
                cbxDepartamento.setSelectedIndex(empleado.getIdDepartament());
                cbxEstadoCivil.setSelectedIndex(empleado.getIdMaritalStatus());
                cbxGenero.setSelectedIndex(empleado.getIdGender());
                cbxTipoDocumento.setSelectedIndex(empleado.getIdIdentityType());

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Empleado", 1);
        }

    }//GEN-LAST:event_btnBuscarEmpleadoActionPerformed

    private void btnEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadoActionPerformed
        String numeroDoc = txtNumeroDocumento.getText();
        String primerNom = txtPrimerNombre.getText();
        String segundNom = txtSegundoNombre.getText();
        String primerApell = txtPrimerApellido.getText();
        String segundoApell = txtSegundoApellido.getText();
        String fechaNacimiento = txtFechaNacimiento.getText();
        String direccion = txtDireccion.getText();
        String barrio = txtBarrio.getText();
        String telFijo = txtTelefonoFijo.getText();
        String celular = txtTelefonoMovil.getText();
        String correo = txtEmail.getText();
        
        try {
            int idEmpleado = Integer.parseInt(txtidEmpleado.getText());
            int idTipoDocumento = cbxTipoDocumento.getSelectedIndex();
            int idEmpresa = 1;
            int idEstadoCivil = cbxEstadoCivil.getSelectedIndex();
            int idGenero = cbxGenero.getSelectedIndex();
            int idCiudad = cbxCiudad.getSelectedIndex();
            int idDepartamento = cbxDepartamento.getSelectedIndex();
            
            clsEmployed empleado = new clsEmployed(idEmpleado, numeroDoc, primerNom, segundNom, primerApell, segundoApell, fechaNacimiento, direccion, barrio, telFijo, celular, correo, idTipoDocumento, idEmpresa, idEstadoCivil, idGenero, idCiudad, idDepartamento, null);
            boolean respuesta = ctlempleado.updateEmpleado(empleado);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarEmpleadoActionPerformed

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        try {
            String numeroDoc = txtNumeroDocumento.getText();
            boolean respuesta = ctlempleado.deleteEmpleado(numeroDoc);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Documento Empleado no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Empleado", 1);
        }
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmployed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmployed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmployed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmployed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmployed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnCrearEmpleado;
    private javax.swing.JButton btnEditarEmpleado;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCiudad;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JComboBox<String> cbxTipoDocumento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBarrio;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNumeroDocumento;
    private javax.swing.JLabel lblPrimerApellido;
    private javax.swing.JLabel lblPrimerNombre;
    private javax.swing.JLabel lblSegundoApellido;
    private javax.swing.JLabel lblSegundoNombre;
    private javax.swing.JLabel lblTelefonoFijo;
    private javax.swing.JLabel lblTelefonoMovil;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtBarrio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefonoFijo;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtidEmpleado;
    // End of variables declaration//GEN-END:variables
}
