/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Class.clsGender;
import Controller.ctlGender;

/**
 *
 * @author andres.rubiano
 */
public class frmGender extends javax.swing.JFrame {

    ctlGender ctlGenero;
    LinkedList<clsGender> listaGenero = new LinkedList<>();
    DefaultTableModel modelTablaGenero = new DefaultTableModel();

    /**
     * Creates new form frmGender
     */
    public frmGender() {
        initComponents();
        this.ctlGenero = new ctlGender();
        this.listaGenero = ctlGenero.ListGenero();
        this.setEncabezado();
        this.setFilasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListGeneros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoGenero = new javax.swing.JTextField();
        txtNombreGenero = new javax.swing.JTextField();
        txtSiglaGenero = new javax.swing.JTextField();
        lblCodigoGenero = new javax.swing.JLabel();
        lblNombreGenero = new javax.swing.JLabel();
        lblSigla = new javax.swing.JLabel();
        btnCrearGenero = new javax.swing.JButton();
        btnEliminarGenero = new javax.swing.JButton();
        btnBuscarGenero = new javax.swing.JButton();
        btnEditarGenero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de Generos");

        tblListGeneros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListGeneros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Genero", jPanel1);

        lblCodigoGenero.setText("Codigo Genero");

        lblNombreGenero.setText("Nombre Genero");

        lblSigla.setText("Sigla");

        btnCrearGenero.setText("Guardar");
        btnCrearGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearGeneroActionPerformed(evt);
            }
        });

        btnEliminarGenero.setText("Eliminar");
        btnEliminarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarGeneroActionPerformed(evt);
            }
        });

        btnBuscarGenero.setText("Buscar");
        btnBuscarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarGeneroActionPerformed(evt);
            }
        });

        btnEditarGenero.setText("Editar");
        btnEditarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarGeneroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearGenero)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarGenero)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarGenero)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarGenero))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoGenero)
                            .addComponent(lblNombreGenero)
                            .addComponent(lblSigla))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSiglaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCodigoGenero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoGenero)
                    .addComponent(txtCodigoGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreGenero)
                    .addComponent(txtNombreGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSigla)
                    .addComponent(txtSiglaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearGenero)
                    .addComponent(btnEliminarGenero)
                    .addComponent(btnBuscarGenero)
                    .addComponent(btnEditarGenero))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoGenero.setText("");
        txtNombreGenero.setText("");
        txtSiglaGenero.setText("");
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo", "Nombre Genero", "Siglas"};
        modelTablaGenero.setColumnIdentifiers(cabecera);
        tblListGeneros.setModel(modelTablaGenero);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaGenero.getColumnCount()];
        int index = 1;
        
        for(clsGender listGenero : listaGenero){

            data[0] = listGenero.getCodeGender();
            data[1] = listGenero.getNameGender();
            data[2] = listGenero.getInitials();
            index++;
            modelTablaGenero.addRow(data);
        }
        tblListGeneros.setModel(modelTablaGenero);
    }

    private void btnCrearGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearGeneroActionPerformed
        try {
            String codigoGenero = txtCodigoGenero.getText();
            String nomGenero = txtNombreGenero.getText();
            String nomSigla = txtSiglaGenero.getText();

            if(codigoGenero.equals("") || nomGenero.equals("") || nomSigla.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos", "Error Informacion Genero", 1);
            }else{
                clsGender genero = new clsGender(codigoGenero, nomGenero, nomSigla);
                ctlGenero.createGenero(genero);
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnCrearGeneroActionPerformed

    private void btnBuscarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarGeneroActionPerformed
        try {
            
            String codigoGenero = txtCodigoGenero.getText();
            clsGender genero = (clsGender) ctlGenero.searchGenero(codigoGenero);

            if(genero == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de Genero no Encontrado");
                
            }else{
                txtCodigoGenero.setText(genero.getCodeGender());
                txtNombreGenero.setText(genero.getNameGender());
                txtSiglaGenero.setText(genero.getInitials());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Genero", 1);
        }

    }//GEN-LAST:event_btnBuscarGeneroActionPerformed

    private void btnEditarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarGeneroActionPerformed
        String codigoGenero = txtCodigoGenero.getText();
        String nomGenero = txtNombreGenero.getText();
        String nomSigla = txtSiglaGenero.getText();

        try {
            clsGender genero = new clsGender(codigoGenero, nomGenero, nomSigla);
            boolean respuesta = ctlGenero.updateGenero(genero);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }

    }//GEN-LAST:event_btnEditarGeneroActionPerformed

    private void btnEliminarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarGeneroActionPerformed
        try {
            String codigoGenero = txtCodigoGenero.getText();
            boolean respuesta = ctlGenero.deleteGenero(codigoGenero);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Departamento", 1);
        }
    }//GEN-LAST:event_btnEliminarGeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarGenero;
    private javax.swing.JButton btnCrearGenero;
    private javax.swing.JButton btnEditarGenero;
    private javax.swing.JButton btnEliminarGenero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoGenero;
    private javax.swing.JLabel lblNombreGenero;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JTable tblListGeneros;
    private javax.swing.JTextField txtCodigoGenero;
    private javax.swing.JTextField txtNombreGenero;
    private javax.swing.JTextField txtSiglaGenero;
    // End of variables declaration//GEN-END:variables
}
