/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.LinkedList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Class.clsEmployed;
import Class.clsReference;
import Controller.ctlEmployed;
import Controller.ctlReference;

/**
 *
 * @author andres.rubiano
 */
public class frmReference extends javax.swing.JFrame {
    ctlReference ctlReferencias;
    ctlEmployed ctlEmpleado;
    LinkedList<clsReference> listaReferencias = new LinkedList<>();
    LinkedList<clsEmployed> listaEmpleado = new LinkedList<>();
    DefaultTableModel modelTablaReferencias = new DefaultTableModel();
    /**
     * Creates new form frmReference
     */
    public frmReference() {
        initComponents();
        txtidReferencia.setVisible(false);
        this.ctlReferencias = new ctlReference();
        this.ctlEmpleado = new ctlEmployed();
        this.listaReferencias = ctlReferencias.ListReferencias();
        this.listaEmpleado = ctlEmpleado.ListEmpleado();
        this.setEncabezado();
        this.setFilasTabla();
        this.LlenarCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtGeneradoPor = new javax.swing.JTextField();
        txtTelefonoFijo = new javax.swing.JTextField();
        lblDeQuienEs = new javax.swing.JLabel();
        lblTelefonoFijo = new javax.swing.JLabel();
        btnEditarReferencia = new javax.swing.JButton();
        btnEliminarReferencia = new javax.swing.JButton();
        btnBuscarReferencia = new javax.swing.JButton();
        lblTelefonoMovil = new javax.swing.JLabel();
        txtTelefonoMovil = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmpleado = new javax.swing.JLabel();
        btnCrearReferencia = new javax.swing.JButton();
        cbxEmpleado = new javax.swing.JComboBox<>();
        txtidReferencia = new javax.swing.JTextField();
        lblCodigoReferencia = new javax.swing.JLabel();
        txtCodigoReferencia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListReferencias = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Referencias");

        lblDeQuienEs.setText("Generado Por");

        lblTelefonoFijo.setText("Telefono Fijo");

        btnEditarReferencia.setText("Editar");
        btnEditarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarReferenciaActionPerformed(evt);
            }
        });

        btnEliminarReferencia.setText("Eliminar");
        btnEliminarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarReferenciaActionPerformed(evt);
            }
        });

        btnBuscarReferencia.setText("Buscar");
        btnBuscarReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarReferenciaActionPerformed(evt);
            }
        });

        lblTelefonoMovil.setText("Telefono Movil");

        lblEmail.setText("Correo Electronico");

        lblEmpleado.setText("Empleado Referencia");

        btnCrearReferencia.setText("Crear");
        btnCrearReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearReferenciaActionPerformed(evt);
            }
        });

        cbxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCodigoReferencia.setText("Codigo Ref");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtidReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnCrearReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarReferencia)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmpleado)
                    .addComponent(lblEmail)
                    .addComponent(lblTelefonoMovil)
                    .addComponent(lblTelefonoFijo)
                    .addComponent(lblDeQuienEs)
                    .addComponent(lblCodigoReferencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCodigoReferencia)
                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGeneradoPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(cbxEmpleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoReferencia)
                    .addComponent(txtCodigoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeQuienEs)
                    .addComponent(txtGeneradoPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoFijo)
                    .addComponent(txtTelefonoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoMovil)
                    .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmpleado)
                    .addComponent(cbxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarReferencia)
                    .addComponent(btnBuscarReferencia)
                    .addComponent(btnCrearReferencia)
                    .addComponent(btnEditarReferencia))
                .addGap(15, 15, 15)
                .addComponent(txtidReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        tblListReferencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListReferencias);

        jTabbedPane1.addTab("Listado Referencias", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoReferencia.setText("");
        txtidReferencia.setText("");
        txtGeneradoPor.setText("");
        txtTelefonoFijo.setText("");
        txtTelefonoMovil.setText("");
        txtEmail.setText("");
        
    }

    private void LlenarCombobox(){
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        int index = 0;
        modelo.addElement("Seleccione una Opcion");
        for(clsEmployed listEmpleado : listaEmpleado){
            String data = listEmpleado.getFirtsName();
            modelo.addElement(data);
            index++;
        }
        this.cbxEmpleado.setModel(modelo);
        
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo Referencia", "Generada por:", "Telefono", "Movil", "Correo"};
        modelTablaReferencias.setColumnIdentifiers(cabecera);
        tblListReferencias.setModel(modelTablaReferencias);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaReferencias.getColumnCount()];
        int index = 1;
        
        for(clsReference listDto : listaReferencias){

            data[0] = listDto.getCodeReference();
            data[1] = listDto.getFirtsName();
            data[2] = listDto.getPhone();
            data[3] = listDto.getCellPhone();
            data[4] = listDto.getEmail();
            index++;
            modelTablaReferencias.addRow(data);
        }
        tblListReferencias.setModel(modelTablaReferencias);
    }
    private void btnCrearReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearReferenciaActionPerformed
        try {
            String codRef = txtCodigoReferencia.getText();
            String nombreRef = txtGeneradoPor.getText();
            String telefonoRef = txtTelefonoFijo.getText();;
            String movilRef = txtTelefonoMovil.getText();
            String emailRef = txtEmail.getText();

            if(codRef.equals("") || nombreRef.equals("") || telefonoRef.equals("") || movilRef.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos Codigo Dane, Nombre Ciudad y Departamento", "Error Informacion Departamento", 1);
            }else{
                clsReference referencia = new clsReference(0, codRef, nombreRef, telefonoRef, movilRef, emailRef);
                ctlReferencias.createReferencias(referencia);
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnCrearReferenciaActionPerformed

    private void btnEditarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarReferenciaActionPerformed
        
        int IdRef = Integer.parseInt(txtidReferencia.getText());
        String codRef = txtCodigoReferencia.getText();
        String nombreRef = txtGeneradoPor.getText();
        String telefonoRef = txtTelefonoFijo.getText();;
        String movilRef = txtTelefonoMovil.getText();
        String emailRef = txtEmail.getText();

        try {
            clsReference referencia = new clsReference(IdRef, codRef, nombreRef, telefonoRef, movilRef, emailRef);
            boolean respuesta = ctlReferencias.updateReferencias(referencia);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarReferenciaActionPerformed

    private void btnBuscarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarReferenciaActionPerformed
        try {
            
            String codigoRef = txtCodigoReferencia.getText();
            clsReference referencia = (clsReference) ctlReferencias.searchReferencias(codigoRef);

            if(referencia == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
                
            }else{

                txtCodigoReferencia.setText(referencia.getCodeReference());
                txtidReferencia.setText(referencia.getIdReference()+"");
                txtGeneradoPor.setText(referencia.getFirtsName());
                txtTelefonoFijo.setText(referencia.getPhone());
                txtTelefonoMovil.setText(referencia.getCellPhone());
                txtEmail.setText(referencia.getEmail());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Referencia", 1);
        }
    }//GEN-LAST:event_btnBuscarReferenciaActionPerformed

    private void btnEliminarReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarReferenciaActionPerformed
        try {
            String codigoRef = txtCodigoReferencia.getText();
            boolean respuesta = ctlReferencias.deleteReferencias(codigoRef);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de la Referencia no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Referencia", 1);
        }
    }//GEN-LAST:event_btnEliminarReferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReference().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarReferencia;
    private javax.swing.JButton btnCrearReferencia;
    private javax.swing.JButton btnEditarReferencia;
    private javax.swing.JButton btnEliminarReferencia;
    private javax.swing.JComboBox<String> cbxEmpleado;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoReferencia;
    private javax.swing.JLabel lblDeQuienEs;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblTelefonoFijo;
    private javax.swing.JLabel lblTelefonoMovil;
    private javax.swing.JTable tblListReferencias;
    private javax.swing.JTextField txtCodigoReferencia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGeneradoPor;
    private javax.swing.JTextField txtTelefonoFijo;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtidReferencia;
    // End of variables declaration//GEN-END:variables
}
