/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.clsMaritalStatus;
import Class.clsTypeDocument;
import Controller.ctlStatusMarital;
import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres.rubiano
 */
public class frmStatusMarital extends javax.swing.JFrame {
    ctlStatusMarital ctlEstadoCivil;
    LinkedList<clsMaritalStatus> listaEstadoCivil = new LinkedList<>();
    DefaultTableModel modelTablaEstadoCivil = new DefaultTableModel();
    /**
     * Creates new form frmStatusMarital
     */
    public frmStatusMarital() {
        initComponents();
        this.ctlEstadoCivil = new ctlStatusMarital();
        this.listaEstadoCivil = ctlEstadoCivil.ListEstadoCivil();
        this.setEncabezado();
        this.setFilasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListEstadoCivil = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoEstadoCivil = new javax.swing.JTextField();
        txtNombreEstadoCivil = new javax.swing.JTextField();
        lblCodigoEstadoCivil = new javax.swing.JLabel();
        lblNombreEstadoCivil = new javax.swing.JLabel();
        btnEditarEstadoCivil = new javax.swing.JButton();
        btnEliminarEstadoCivil = new javax.swing.JButton();
        btnBuscarEstadoCivil = new javax.swing.JButton();
        btnCrearEstadoCivil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion Estado Civil");

        tblListEstadoCivil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListEstadoCivil);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Estado Civil", jPanel1);

        lblCodigoEstadoCivil.setText("Codigo");

        lblNombreEstadoCivil.setText("Estado Civil");

        btnEditarEstadoCivil.setText("Editar");
        btnEditarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEstadoCivilActionPerformed(evt);
            }
        });

        btnEliminarEstadoCivil.setText("Eliminar");
        btnEliminarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstadoCivilActionPerformed(evt);
            }
        });

        btnBuscarEstadoCivil.setText("Buscar");
        btnBuscarEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstadoCivilActionPerformed(evt);
            }
        });

        btnCrearEstadoCivil.setText("Guardar");
        btnCrearEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodigoEstadoCivil)
                    .addComponent(lblNombreEstadoCivil)
                    .addComponent(btnCrearEstadoCivil))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarEstadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarEstadoCivil)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarEstadoCivil)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoEstadoCivil)
                    .addComponent(txtCodigoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEstadoCivil)
                    .addComponent(txtNombreEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarEstadoCivil)
                    .addComponent(btnBuscarEstadoCivil)
                    .addComponent(btnCrearEstadoCivil)
                    .addComponent(btnEditarEstadoCivil))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void limpiarCampos(){
        txtCodigoEstadoCivil.setText("");
        txtNombreEstadoCivil.setText("");
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo", "Estado Civil"};
        modelTablaEstadoCivil.setColumnIdentifiers(cabecera);
        tblListEstadoCivil.setModel(modelTablaEstadoCivil);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaEstadoCivil.getColumnCount()];
        int index = 1;
        
        for(clsMaritalStatus listEstadoCivil : listaEstadoCivil){

            data[0] = listEstadoCivil.getCodeMaritalStatus();
            data[1] = listEstadoCivil.getNameStatus();
            index++;
            modelTablaEstadoCivil.addRow(data);
        }
        tblListEstadoCivil.setModel(modelTablaEstadoCivil);
    }
    private void btnCrearEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEstadoCivilActionPerformed
        try {
            String codigoEstadoCivil = txtCodigoEstadoCivil.getText();
            String nomEstadoCivil = txtNombreEstadoCivil.getText();

            if(codigoEstadoCivil.equals("") || nomEstadoCivil.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos", "Error Informacion EstadoCivil", 1);
            }else{
                clsMaritalStatus estadoCivil = new clsMaritalStatus(nomEstadoCivil, codigoEstadoCivil);
                ctlEstadoCivil.createEstadoCivil(estadoCivil);
                this.limpiarCampos();
                this.listaEstadoCivil = ctlEstadoCivil.ListEstadoCivil();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnCrearEstadoCivilActionPerformed

    private void btnBuscarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstadoCivilActionPerformed
        try {
            
            String codigoEstadoCivil = txtCodigoEstadoCivil.getText();
            clsMaritalStatus estadoCivil = (clsMaritalStatus) ctlEstadoCivil.searchEstadoCivil(codigoEstadoCivil);

            if(estadoCivil == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de EstadoCivil no Encontrado");
                
            }else{

                txtCodigoEstadoCivil.setText(estadoCivil.getCodeMaritalStatus());
                txtNombreEstadoCivil.setText(estadoCivil.getNameStatus());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En EstadoCivil", 1);
        }
    }//GEN-LAST:event_btnBuscarEstadoCivilActionPerformed

    private void btnEditarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEstadoCivilActionPerformed
        String codigoEstadoCivil = txtCodigoEstadoCivil.getText();
        String nomEstadoCivil = txtNombreEstadoCivil.getText();

        try {
            clsMaritalStatus estadoCivil = new clsMaritalStatus(nomEstadoCivil, codigoEstadoCivil);
            boolean respuesta = ctlEstadoCivil.updateEstadoCivil(estadoCivil);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarEstadoCivilActionPerformed

    private void btnEliminarEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstadoCivilActionPerformed
        try {
            String codigoEstadoCivil = txtCodigoEstadoCivil.getText();
            boolean respuesta = ctlEstadoCivil.deleteEstadoCivil(codigoEstadoCivil);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Departamento", 1);
        }
    }//GEN-LAST:event_btnEliminarEstadoCivilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmStatusMarital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmStatusMarital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmStatusMarital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmStatusMarital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmStatusMarital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstadoCivil;
    private javax.swing.JButton btnCrearEstadoCivil;
    private javax.swing.JButton btnEditarEstadoCivil;
    private javax.swing.JButton btnEliminarEstadoCivil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoEstadoCivil;
    private javax.swing.JLabel lblNombreEstadoCivil;
    private javax.swing.JTable tblListEstadoCivil;
    private javax.swing.JTextField txtCodigoEstadoCivil;
    private javax.swing.JTextField txtNombreEstadoCivil;
    // End of variables declaration//GEN-END:variables
}
