/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.clsTypeDocument;
import Controller.ctlTypeDocument;
import java.util.LinkedList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres.rubiano
 */
public class frmTypeDocument extends javax.swing.JFrame {
    
    ctlTypeDocument ctlTipoDocumento;
    LinkedList<clsTypeDocument> listaTipoDocumento = new LinkedList<>();
    DefaultTableModel modelTablaTipoDocumento = new DefaultTableModel();

    /**
     * Creates new form frmTypeDocument
     */
    public frmTypeDocument() {
        initComponents();
        this.ctlTipoDocumento = new ctlTypeDocument();
        this.listaTipoDocumento = ctlTipoDocumento.ListTipoDocumentos();
        this.setEncabezado();
        this.setFilasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListTipoDocumento = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoTipoDocumento = new javax.swing.JTextField();
        txtNombreTipoDocumento = new javax.swing.JTextField();
        lblCodigoTipoDocumento = new javax.swing.JLabel();
        lblNombreTipoDocumento = new javax.swing.JLabel();
        btnCrearTipoDocumento = new javax.swing.JButton();
        btnEliminarTipoDocumento = new javax.swing.JButton();
        btnBuscarTipoDocumento = new javax.swing.JButton();
        btnEditarTipoDocumento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion de Tipo Documento");

        tblListTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListTipoDocumento);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Tipo Documento", jPanel1);

        lblCodigoTipoDocumento.setText("Codigo");

        lblNombreTipoDocumento.setText("Tipo de Documento");

        btnCrearTipoDocumento.setText("Guardar");
        btnCrearTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoDocumentoActionPerformed(evt);
            }
        });

        btnEliminarTipoDocumento.setText("Eliminar");
        btnEliminarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoDocumentoActionPerformed(evt);
            }
        });

        btnBuscarTipoDocumento.setText("Buscar");
        btnBuscarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTipoDocumentoActionPerformed(evt);
            }
        });

        btnEditarTipoDocumento.setText("Editar");
        btnEditarTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoDocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoTipoDocumento)
                            .addComponent(lblNombreTipoDocumento))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCrearTipoDocumento)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarTipoDocumento)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarTipoDocumento)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTipoDocumento)
                        .addGap(28, 28, 28))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoTipoDocumento)
                    .addComponent(txtCodigoTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTipoDocumento)
                    .addComponent(txtNombreTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTipoDocumento)
                    .addComponent(btnEliminarTipoDocumento)
                    .addComponent(btnBuscarTipoDocumento)
                    .addComponent(btnEditarTipoDocumento))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoTipoDocumento.setText("");
        txtNombreTipoDocumento.setText("");
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo", "Tipo de Documento"};
        modelTablaTipoDocumento.setColumnIdentifiers(cabecera);
        tblListTipoDocumento.setModel(modelTablaTipoDocumento);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaTipoDocumento.getColumnCount()];
        int index = 1;
        
        for(clsTypeDocument listTDocumentos : listaTipoDocumento){

            data[0] = listTDocumentos.getCodeType();
            data[1] = listTDocumentos.getNameDocument();
            index++;
            modelTablaTipoDocumento.addRow(data);
        }
        tblListTipoDocumento.setModel(modelTablaTipoDocumento);
    }
    private void btnCrearTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoDocumentoActionPerformed
        try {
            String codigoTDocumento = txtCodigoTipoDocumento.getText();
            String nomTDocumento = txtNombreTipoDocumento.getText();

            if(codigoTDocumento.equals("") || nomTDocumento.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos", "Error Informacion Tipo Documento", 1);
            }else{
                clsTypeDocument tipoDocumento = new clsTypeDocument(nomTDocumento, codigoTDocumento);
                ctlTipoDocumento.createTipoDocumento(tipoDocumento);
                this.limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }
    }//GEN-LAST:event_btnCrearTipoDocumentoActionPerformed

    private void btnBuscarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTipoDocumentoActionPerformed
        try {
            
            String codigoTDocumento = txtCodigoTipoDocumento.getText();
            clsTypeDocument tipoDocumento = (clsTypeDocument) ctlTipoDocumento.searchTipoDocumento(codigoTDocumento);

            if(tipoDocumento == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de TipoDocumento no Encontrado");
                
            }else{
                
                txtCodigoTipoDocumento.setText(tipoDocumento.getCodeType());
                txtNombreTipoDocumento.setText(tipoDocumento.getNameDocument());
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En TipoDocumento", 1);
        }
    }//GEN-LAST:event_btnBuscarTipoDocumentoActionPerformed

    private void btnEditarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoDocumentoActionPerformed
        String codigoTDocumento = txtCodigoTipoDocumento.getText();
        String nomTDocumento = txtNombreTipoDocumento.getText();

        try {
            clsTypeDocument tipoDocumento = new clsTypeDocument(nomTDocumento, codigoTDocumento);
            boolean respuesta = ctlTipoDocumento.updateTipoDocumento(tipoDocumento);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarTipoDocumentoActionPerformed

    private void btnEliminarTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoDocumentoActionPerformed
        try {
            String codigoTDocumento = txtCodigoTipoDocumento.getText();
            boolean respuesta = ctlTipoDocumento.deleteTipoDocumento(codigoTDocumento);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Tipo de Documento", 1);
        }
    }//GEN-LAST:event_btnEliminarTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTypeDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTypeDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTypeDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTypeDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTypeDocument().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTipoDocumento;
    private javax.swing.JButton btnCrearTipoDocumento;
    private javax.swing.JButton btnEditarTipoDocumento;
    private javax.swing.JButton btnEliminarTipoDocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoTipoDocumento;
    private javax.swing.JLabel lblNombreTipoDocumento;
    private javax.swing.JTable tblListTipoDocumento;
    private javax.swing.JTextField txtCodigoTipoDocumento;
    private javax.swing.JTextField txtNombreTipoDocumento;
    // End of variables declaration//GEN-END:variables
}
