/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Class.clsTypeReference;
import Controller.ctlTypeReference;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andres.rubiano
 */
public class frmTypeReference extends javax.swing.JFrame {
    
    ctlTypeReference ctlTipoReferencia;
    LinkedList<clsTypeReference> listaTipoReferencias = new LinkedList<>();
    DefaultTableModel modelTablaTipoReferencia = new DefaultTableModel();
    /**
     * Creates new form frmTypeReference
     */
    public frmTypeReference() {
        initComponents();
        this.ctlTipoReferencia = new ctlTypeReference();
        this.listaTipoReferencias = ctlTipoReferencia.listTypeReferences();
        this.setEncabezado();
        this.setFilasTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaTipoReferencia = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtCodigoTipoReferencia = new javax.swing.JTextField();
        txtNombreTipoReferencia = new javax.swing.JTextField();
        lblCodigoTipoReferencia = new javax.swing.JLabel();
        lblNombreTipoReferencia = new javax.swing.JLabel();
        btnCrearTipoReferencia = new javax.swing.JButton();
        btnEliminarTipoReferencia = new javax.swing.JButton();
        btnBuscarTipoReferencia = new javax.swing.JButton();
        btnEditarTipoReferencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuracion Tipo de Referencia");

        tblListaTipoReferencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaTipoReferencia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listado Tipo Referencias", jPanel1);

        lblCodigoTipoReferencia.setText("Codigo");

        lblNombreTipoReferencia.setText("Tipo de Referencia");

        btnCrearTipoReferencia.setText("Guardar");
        btnCrearTipoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearTipoReferenciaActionPerformed(evt);
            }
        });

        btnEliminarTipoReferencia.setText("Eliminar");
        btnEliminarTipoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTipoReferenciaActionPerformed(evt);
            }
        });

        btnBuscarTipoReferencia.setText("Buscar");
        btnBuscarTipoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTipoReferenciaActionPerformed(evt);
            }
        });

        btnEditarTipoReferencia.setText("Editar");
        btnEditarTipoReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTipoReferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigoTipoReferencia)
                            .addComponent(lblNombreTipoReferencia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearTipoReferencia)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreTipoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoTipoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarTipoReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarTipoReferencia)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTipoReferencia)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoTipoReferencia)
                    .addComponent(txtCodigoTipoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreTipoReferencia)
                    .addComponent(txtNombreTipoReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearTipoReferencia)
                    .addComponent(btnEliminarTipoReferencia)
                    .addComponent(btnBuscarTipoReferencia)
                    .addComponent(btnEditarTipoReferencia))
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("Formulario", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txtCodigoTipoReferencia.setText("");
        txtNombreTipoReferencia.setText("");
    }

    private void setEncabezado(){
        String[] cabecera = {"Codigo", "Tipo de Referencia"};
        modelTablaTipoReferencia.setColumnIdentifiers(cabecera);
        tblListaTipoReferencia.setModel(modelTablaTipoReferencia);
    }

    private void setFilasTabla(){
        
        Object[] data = new Object[modelTablaTipoReferencia.getColumnCount()];
        int index = 1;
        
        for(clsTypeReference listTReferencias : listaTipoReferencias){

            data[0] = listTReferencias.getCodeReference();
            data[1] = listTReferencias.getNameReference();
            index++;
            modelTablaTipoReferencia.addRow(data);
        }
        tblListaTipoReferencia.setModel(modelTablaTipoReferencia);
    }
    
    
    private void btnCrearTipoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearTipoReferenciaActionPerformed
        try {
            String codigoTReferencia = txtCodigoTipoReferencia.getText();
            String nomTReferencia = txtNombreTipoReferencia.getText();

            if(codigoTReferencia.equals("") || nomTReferencia.equals("")){
                JOptionPane.showMessageDialog(this, "Informacion Vacia en los campos", "Error Informacion Tipo Referencia", 1);
            }else{
                clsTypeReference referencia = new clsTypeReference(codigoTReferencia, nomTReferencia);
                ctlTipoReferencia.createTipoReferencia(referencia);
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Informacion Guardada con Exito", "Confirmacion de Almacenamiento", 1);
            }
        } catch (Exception e) {
            //TODO: handle exception
        }

    }//GEN-LAST:event_btnCrearTipoReferenciaActionPerformed

    private void btnBuscarTipoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTipoReferenciaActionPerformed
        try {
            
            String codigoTReferencia = txtCodigoTipoReferencia.getText();
            clsTypeReference tipoReferencia = (clsTypeReference) ctlTipoReferencia.searchTipoReferencia(codigoTReferencia);

            if(tipoReferencia == null){
                
                JOptionPane.showMessageDialog(this, "Codigo de Tipo Referencia no Encontrado");
                
            }else{
                txtCodigoTipoReferencia.setText(tipoReferencia.getCodeReference());
                txtNombreTipoReferencia.setText(tipoReferencia.getNameReference());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Tipo Referencia", 1);
        }
    }//GEN-LAST:event_btnBuscarTipoReferenciaActionPerformed

    private void btnEditarTipoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTipoReferenciaActionPerformed
        String codigoTReferencia = txtCodigoTipoReferencia.getText();
        String nomTReferencia = txtNombreTipoReferencia.getText();
        

        try {
            clsTypeReference tipoReferencia = new clsTypeReference(codigoTReferencia, nomTReferencia);
            boolean respuesta = ctlTipoReferencia.updateTipoReferencia(tipoReferencia);

            if(respuesta){
                limpiarCampos();
                JOptionPane.showMessageDialog(this, "Registro Actualizado", "Confirmacion!", 2);
            }else{
                JOptionPane.showMessageDialog(this, "Error al Actualizar", "Error de Actualizacion", 1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Actualizar" + e, "Error de Actualizacion", 1);
        }
    }//GEN-LAST:event_btnEditarTipoReferenciaActionPerformed

    private void btnEliminarTipoReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTipoReferenciaActionPerformed
        try {
            String codigoTReferencia = txtCodigoTipoReferencia.getText();
            boolean respuesta = ctlTipoReferencia.deleteTipoReferencia(codigoTReferencia);

            if(respuesta){
                this.limpiarCampos();
                    JOptionPane.showMessageDialog(this, "Informacion Eliminada Correctamente!");
            }else{
                JOptionPane.showMessageDialog(this, "Codigo de Departamento no Encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Por favor Valide la Informacion", "Error En Departamento", 1);
        }
    }//GEN-LAST:event_btnEliminarTipoReferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTypeReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTypeReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTypeReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTypeReference.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTypeReference().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarTipoReferencia;
    private javax.swing.JButton btnCrearTipoReferencia;
    private javax.swing.JButton btnEditarTipoReferencia;
    private javax.swing.JButton btnEliminarTipoReferencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoTipoReferencia;
    private javax.swing.JLabel lblNombreTipoReferencia;
    private javax.swing.JTable tblListaTipoReferencia;
    private javax.swing.JTextField txtCodigoTipoReferencia;
    private javax.swing.JTextField txtNombreTipoReferencia;
    // End of variables declaration//GEN-END:variables
}
